import react from "react";

const NewNftsDetails = [
  {
    id: 1,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 2,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 3,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 4,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 5,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 6,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 7,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
  {
    id: 8,
    nftImg: "image_interview_react/liveauctions.png",
    cardTitle: "Women NFT #325",
    cardRating: {
      star1: "gold",
      star2: "gold",
      star3: "gold",
      star4: "",
      star5: "",
    },
    cardRate: "15,000",
    cardBuyerFirstImg: "image_interview_react/liveauctions.png",
    cardBuyerSecondImg: "image_interview_react/liveauctions.png",
    cardBuyerEmail: "@ robert03",
    cardBuyerName: "by lorem ipsum",
    cardLikes: "246",
  },
];

export default NewNftsDetails;
